<?php require_once('./templates/header.phtml'); ?>
<div class="container mt-5">
    <h1>Categorias Actualizadas</h1>
    <div class="table-responsive"> 
        <table class="table table-hover"> 
            <thead class="thead-light"> 
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Season</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($categories as $category): ?>
                <tr>
                    <td><?php echo $category->id ?></td>
                    <td><?php echo $category->name ?></td>
                    <td><?php echo $category->season ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require_once('./templates/footer.phtml'); ?>



<div class="container mt-5">
    <h1>Categorias Actualizadas</h1>
    <div class="table-responsive"> 
        <table class="table table-hover"> 
            <thead class="thead-light"> 
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Season</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($categories as $category): ?>
                <tr>
                    <td><?php echo $category->id ?></td>
                    <td><?php echo $category->name ?></td>
                    <td><?php echo $category->season ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
